apiVersion: v1
kind: Service
metadata:
  creationTimestamp: '2026-06-18T11:56:04Z'
  managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:spec:
          f:internalTrafficPolicy: {}
          f:ports:
            .: {}
            k:{"port":8080,"protocol":"TCP"}:
              .: {}
              f:name: {}
              f:port: {}
              f:protocol: {}
              f:targetPort: {}
            k:{"port":52425,"protocol":"TCP"}:
              .: {}
              f:name: {}
              f:port: {}
              f:protocol: {}
              f:targetPort: {}
            k:{"port":54286,"protocol":"TCP"}:
              .: {}
              f:name: {}
              f:port: {}
              f:protocol: {}
              f:targetPort: {}
          f:selector: {}
          f:sessionAffinity: {}
          f:type: {}
      manager: agent
      operation: Update
      time: '2026-06-22T05:52:55Z'
  name: nest-desktop
  namespace: nest-desktop
  resourceVersion: '43760757'
  uid: b8db7a2e-633c-4d71-807d-e237da11cd14
spec:
  clusterIP: 10.43.103.31
  clusterIPs:
    - 10.43.103.31
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: auth
      port: 8080
      protocol: TCP
      targetPort: ebrains-auth
    - name: frontend
      port: 54286
      protocol: TCP
      targetPort: frontend
    - name: nest
      port: 52425
      protocol: TCP
      targetPort: nest
  selector:
    io.kompose.service: nest-desktop
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
