apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: '2'
  creationTimestamp: '2026-06-22T05:49:23Z'
  generation: 2
  labels:
    io.kompose.service: nest-desktop
    workload.user.cattle.io/workloadselector: apps.deployment-nest-desktop-apps.prod-jsccloud.ebrains.eu
  managedFields:
    - apiVersion: apps/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations: {}
          f:labels:
            .: {}
            f:io.kompose.service: {}
            f:workload.user.cattle.io/workloadselector: {}
        f:spec:
          f:progressDeadlineSeconds: {}
          f:replicas: {}
          f:revisionHistoryLimit: {}
          f:selector: {}
          f:strategy:
            f:rollingUpdate:
              .: {}
              f:maxSurge: {}
              f:maxUnavailable: {}
            f:type: {}
          f:template:
            f:metadata:
              f:annotations:
                .: {}
                f:cattle.io/timestamp: {}
              f:labels:
                .: {}
                f:io.kompose.service: {}
                f:workload.user.cattle.io/workloadselector: {}
              f:name: {}
              f:namespace: {}
            f:spec:
              f:containers:
                k:{"name":"apache2-oidc"}:
                  .: {}
                  f:env:
                    .: {}
                    k:{"name":"HOSTNAME"}:
                      .: {}
                      f:name: {}
                      f:value: {}
                    k:{"name":"OIDC_CLIENT_ID"}:
                      .: {}
                      f:name: {}
                      f:value: {}
                    k:{"name":"OIDC_CLIENT_SECRET"}:
                      .: {}
                      f:name: {}
                      f:valueFrom:
                        .: {}
                        f:secretKeyRef: {}
                    k:{"name":"OIDC_CRYPTO_PASSPHRASE"}:
                      .: {}
                      f:name: {}
                      f:valueFrom:
                        .: {}
                        f:configMapKeyRef: {}
                    k:{"name":"OIDC_ISSUER"}:
                      .: {}
                      f:name: {}
                      f:valueFrom:
                        .: {}
                        f:configMapKeyRef: {}
                  f:image: {}
                  f:imagePullPolicy: {}
                  f:name: {}
                  f:ports:
                    .: {}
                    k:{"containerPort":8080,"protocol":"TCP"}:
                      .: {}
                      f:containerPort: {}
                      f:name: {}
                      f:protocol: {}
                  f:resources: {}
                  f:securityContext:
                    .: {}
                    f:allowPrivilegeEscalation: {}
                    f:capabilities:
                      .: {}
                      f:drop: {}
                    f:privileged: {}
                    f:readOnlyRootFilesystem: {}
                    f:runAsNonRoot: {}
                  f:terminationMessagePath: {}
                  f:terminationMessagePolicy: {}
                  f:volumeMounts:
                    .: {}
                    k:{"mountPath":"/etc/apache2/sites-enabled/"}:
                      .: {}
                      f:mountPath: {}
                      f:name: {}
              f:dnsPolicy: {}
              f:restartPolicy: {}
              f:schedulerName: {}
              f:securityContext: {}
              f:terminationGracePeriodSeconds: {}
              f:volumes:
                .: {}
                k:{"name":"volume-apache2-config"}:
                  .: {}
                  f:configMap:
                    .: {}
                    f:defaultMode: {}
                    f:name: {}
                  f:name: {}
      manager: agent
      operation: Update
      time: '2026-06-22T05:52:26Z'
    - apiVersion: apps/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            f:deployment.kubernetes.io/revision: {}
        f:status:
          f:availableReplicas: {}
          f:conditions:
            .: {}
            k:{"type":"Available"}:
              .: {}
              f:lastTransitionTime: {}
              f:lastUpdateTime: {}
              f:message: {}
              f:reason: {}
              f:status: {}
              f:type: {}
            k:{"type":"Progressing"}:
              .: {}
              f:lastTransitionTime: {}
              f:lastUpdateTime: {}
              f:message: {}
              f:reason: {}
              f:status: {}
              f:type: {}
          f:observedGeneration: {}
          f:readyReplicas: {}
          f:replicas: {}
          f:updatedReplicas: {}
      manager: kube-controller-manager
      operation: Update
      subresource: status
      time: '2026-06-22T05:52:28Z'
  name: apps.prod-jsccloud.ebrains.eu
  namespace: nest-desktop
  resourceVersion: '43760538'
  uid: 22308791-25f6-49d5-a84f-d1a08ddf48ef
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.deployment-nest-desktop-apps.prod-jsccloud.ebrains.eu
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        cattle.io/timestamp: '2026-06-19T13:30:13Z'
      labels:
        io.kompose.service: nest-desktop
        workload.user.cattle.io/workloadselector: apps.deployment-nest-desktop-apps.prod-jsccloud.ebrains.eu
      name: apps.prod-jsccloud.ebrains.eu
      namespace: nest-desktop
    spec:
      containers:
        - env:
            - name: HOSTNAME
              value: https://nest-desktop.apps.prod-jsccloud.ebrains.eu
            - name: OIDC_CLIENT_ID
              value: nest-desktop
            - name: OIDC_CRYPTO_PASSPHRASE
              valueFrom:
                configMapKeyRef:
                  key: OIDC_CRYPTO_PASSPHRASE
                  name: iam.ebrains.eu
                  optional: false
            - name: OIDC_ISSUER
              valueFrom:
                configMapKeyRef:
                  key: OIDC_ISSUER
                  name: iam.ebrains.eu
                  optional: false
            - name: OIDC_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  key: OIDC_CLIENT_SECRET
                  name: oidc-client-secret-nest-desktop
                  optional: false
          image: docker-registry.ebrains.eu/nest/apache2-oidc:base
          imagePullPolicy: Always
          name: apache2-oidc
          ports:
            - containerPort: 8080
              name: jsccloud-auth
              protocol: TCP
          resources: {}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: false
            runAsNonRoot: false
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /etc/apache2/sites-enabled/
              name: volume-apache2-config
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - configMap:
            defaultMode: 420
            name: apache2-oidc
          name: volume-apache2-config
status:
  availableReplicas: 1
  conditions:
    - lastTransitionTime: '2026-06-22T05:49:25Z'
      lastUpdateTime: '2026-06-22T05:49:25Z'
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: 'True'
      type: Available
    - lastTransitionTime: '2026-06-22T05:49:23Z'
      lastUpdateTime: '2026-06-22T05:52:28Z'
      message: >-
        ReplicaSet "apps.prod-jsccloud.ebrains.eu-5cbdb97798" has successfully
        progressed.
      reason: NewReplicaSetAvailable
      status: 'True'
      type: Progressing
  observedGeneration: 2
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
